### PR TITLE
Added flake8-docstring and applied Black for code style

### PR DESCRIPTION
**Pull request by schmerl**

### CODE REVIEW

**Comment by schmerl** [comment]
The travis is failing, but is this some kind of setup problem with travis?

**Comment by ChrisTimperley** [comment]
Travis is failing for another reason. We should try to fix that first before we merge this PR.

**Comment by schmerl** [comment]
Ok. At our meeting.

**Comment by schmerl** [comment]
This posted one day ago. https://travis-ci.community/t/cant-deploy-to-pypi-anymore-pkg-resources-contextualversionconflict-importlib-metadata-0-18/10494/9

**Review by ChrisTimperley — APPROVED** [review]
Great. LGTM 👍🏻

**Pull request merged**
