### PR TITLE
Implemented exclude_topics for ROS bag recorder (fixes #7)

### LINKED ISSUE #7: Add proxy for interacting with file system
* [x] #53 read contents of file
* [x] #55 write to file
* [ ] append to file
* [ ] #181 implement `find`-like functionality
* [ ] copy file (i.e., `shutil.copy`)
* [ ] copy tree recursively (i.e., `shutil.copytree`)
* [ ] #47 chmod (i.e., `os.chmod`)
* [x] #40 remove file (i.e., `os.remove`, `rm`)
* [x] #41 remove directory (i.e., `os.rmdir`, `rmdir`)
* [x] #44 remove directory and contents (i.e., `shutil.rmtree`, `rm -r`)
* [x] #35 list contents of directory (i.e., `os.listdir`, `ls`)
* [x] #36 create directory (non-recursive) (i.e., `os.mkdir`)
* [x] #39 create directory (recursive) (i.e., `os.makedirs`)
* [x] #34 check if file/directory exists (i.e., `os.exists`, `os.isfile`, `os.isdir`, `os.islink`)
* [ ] #48 touch (i.e., `os.touch`)
* [x] #50 copy to host (i.e., `docker cp`)
* [x] #51 copy from host (i.e., `docker cp`)
* [x] #121 create temporary file (i.e., `tempfile.mktemp`)
* [ ] #122 create temporary directory (i.e., `tempfile.mkdtemp`)
* [x] #123 temporary file context manager
* [ ] #125 temporary dir context manager

## References
https://docs.python.org/3/library/os.html
https://docs.python.org/3/library/shutil.html

### PR DESCRIPTION
**Pull request by ChrisTimperley**

### CODE REVIEW

**Comment by DebyKatz** [comment]
I got the following error, when using `exclude_topics=['/clock']`:
```Traceback (most recent call last):
  File "run_fetch.py", line 67, in <module>
    main()
  File "run_fetch.py", line 61, in main
    with ros.record(bagfile, exclude_topics=to_exclude) as recorder:
  File "/usr0/home/dskatz/.local/share/virtualenvs/overhead-timing-effects-in-ROS-Wl9qFQgJ/lib/python3.6/site-packages/roswire/proxy/bag.py", line 188, in __enter__
    self.start()
  File "/usr0/home/dskatz/.local/share/virtualenvs/overhead-timing-effects-in-ROS-Wl9qFQgJ/lib/python3.6/site-packages/roswire/proxy/bag.py", line 216, in start
    args += ['-x', shlex.quote(self.__exclude_topics)]
  File "/usr/lib/python3.6/shlex.py", line 314, in quote
    if _find_unsafe(s) is None:
TypeError: expected string or bytes-like object```

**Comment by ChrisTimperley** [comment]
> I got the following error, when using `exclude_topics=['/clock']`:
> 
> ```
>   File "run_fetch.py", line 67, in <module>
>     main()
>   File "run_fetch.py", line 61, in main
>     with ros.record(bagfile, exclude_topics=to_exclude) as recorder:
>   File "/usr0/home/dskatz/.local/share/virtualenvs/overhead-timing-effects-in-ROS-Wl9qFQgJ/lib/python3.6/site-packages/roswire/proxy/bag.py", line 188, in __enter__
>     self.start()
>   File "/usr0/home/dskatz/.local/share/virtualenvs/overhead-timing-effects-in-ROS-Wl9qFQgJ/lib/python3.6/site-packages/roswire/proxy/bag.py", line 216, in start
>     args += ['-x', shlex.quote(self.__exclude_topics)]
>   File "/usr/lib/python3.6/shlex.py", line 314, in quote
>     if _find_unsafe(s) is None:
> TypeError: expected string or bytes-like object```
> ```

Sorry about this. I've changed the API to match the [rosbag record command line](http://wiki.ros.org/rosbag/Commandline#record), which accepts a single regular expression rather than a list of topics (or regular expressions).

**Comment by DebyKatz** [comment]
Ok, this appears to work when using the syntax of a single regex. ROS can be a little sensitive about the regex format, but it appears to work as expected on regexes that `rosbag record --exclude` would accept.

**Comment by ChrisTimperley** [comment]
@DebyKatz, do you think that the name `exclude` rather than `exclude_topics` would do a better job of suggesting that the input is not a list?

**Comment by DebyKatz** [comment]
@ChrisTimperley , maybe, but I think it's a less descriptive and less useful name overall. With the name `exclude`, we might be talking about excluding, e.g., message types instead of topics.

**Pull request merged**
